<a href="?controller=usuarios&action=insert">Insertar usuario</a>
<table border=1>
<tr>
	<th>Id</th>
	<th>Nombre</th>	<th>Email</th>
	<th>Password</th>	<th>Direccion</th>
	<th>Telefono</th>	<th>Descripcion</th>
	<th>Tecnologia</th>	<th>Mascota</th>
	<th>Idiomas</th>	<th>Ciudad</th>
	<th>Submit</th>	<th>Photo</th>
	<th>Options</th>	
</tr>
<?php foreach($users as $key => $user):?>
	<tr>
		<?php foreach ($user as $value):?>
			<td><?=$value;?></td>
		<?php endforeach;?>
		<td>
			<a href="?controller=usuarios&action=update&line=<?=$key;?>">Update</a>
				&nbsp;&nbsp;
			 <a href="?controller=usuarios&action=delete&line=<?=$key;?>">Delete</a>
		</td>
	</tr>
<?php endforeach;?>	
</table>





